#!/usr/bin/env bash
# =============================================================================
#  gen-dev-env.sh — generate a fresh .env file for local Triton development
# =============================================================================
#
# Prints a complete .env file to stdout with freshly-generated Ed25519
# keypairs, random admin credentials, and a matching enterprise-tier
# license token so the whole stack can come up with a single command:
#
#     ./scripts/gen-dev-env.sh > .env
#     podman compose --profile server --profile license-server up -d
#
# Every invocation produces DIFFERENT credentials. Re-running this on an
# existing stack will invalidate all issued tokens and force re-login.
#
# Requires: openssl, xxd, go (to run cmd/keygen for the matching license
# token). No external network access.

set -euo pipefail

# Pretty-print helpers — stderr so they don't pollute the .env output.
err() { printf '%s\n' "$*" >&2; }
die() { err "error: $*"; exit 1; }

command -v openssl >/dev/null || die "openssl not found in PATH"
command -v xxd     >/dev/null || die "xxd not found in PATH"
command -v go      >/dev/null || die "go not found in PATH (required to mint the license token)"

err "generating fresh Ed25519 keypair for the license server…"
# Ed25519 PEM → raw 32-byte seed → hex. `openssl genpkey` emits PKCS#8,
# and the last 32 bytes of the DER-decoded body are the seed.
tmp_pem=$(mktemp)
trap 'rm -f "$tmp_pem"' EXIT
openssl genpkey -algorithm ed25519 -out "$tmp_pem" 2>/dev/null

# Extract the 32-byte seed from the PKCS#8 DER body.
ed25519_seed_hex=$(
    openssl pkey -in "$tmp_pem" -outform DER 2>/dev/null \
        | tail -c 32 \
        | xxd -p -c 64
)
# Derive the matching 32-byte public key.
ed25519_pub_hex=$(
    openssl pkey -in "$tmp_pem" -pubout -outform DER 2>/dev/null \
        | tail -c 32 \
        | xxd -p -c 64
)

# License server private key is the 64-byte concatenation (seed || pubkey)
# — that's the Go ed25519.PrivateKey wire format.
license_signing_key_hex="${ed25519_seed_hex}${ed25519_pub_hex}"

# Shared service key for cross-server provisioning (32 bytes hex).
service_key=$(openssl rand -hex 32)

# Report server JWT signing seed (32 bytes hex — Go will derive the pub half).
jwt_signing_key=$(openssl rand -hex 32)

# First-time superadmin password.
admin_password=$(openssl rand -base64 24)

err "minting enterprise-tier license token signed with the fresh key…"
# Use cmd/keygen to mint a token signed with the freshly-generated key.
# --no-bind so dev hosts can all share the stack without machine binding.
license_token=$(
    go run -tags=keygen ./cmd/keygen \
        -tier enterprise \
        -org "dev-local" \
        -seats 10 \
        -expiry "8760h" \
        -no-bind \
        -signing-key "$license_signing_key_hex" \
        2>/dev/null
) || {
    # Fallback: if cmd/keygen isn't wired with these flags, skip the
    # token mint and leave it blank — operator can issue one via the
    # admin UI after bootstrap.
    err "warning: could not auto-mint a license token (cmd/keygen flags differ); TRITON_LICENSE_KEY will be blank. Mint one manually from the license server admin UI."
    license_token=""
}

cat <<EOF
# Generated by scripts/gen-dev-env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
#
# ⚠  NEVER commit this file. It's already in .gitignore.
# ⚠  These are LOCAL DEVELOPMENT credentials. Do not reuse in production.

# ---- License server ----
TRITON_LICENSE_SERVER_SIGNING_KEY=$license_signing_key_hex
TRITON_LICENSE_SERVER_ADMIN_EMAIL=admin@triton.local
TRITON_LICENSE_SERVER_ADMIN_PASSWORD=$admin_password
TRITON_LICENSE_SERVER_REPORT_KEY=$service_key

# ---- Report server ----
REPORT_SERVER_SERVICE_KEY=$service_key
REPORT_SERVER_JWT_SIGNING_KEY=$jwt_signing_key
REPORT_SERVER_TENANT_PUBKEY=$ed25519_pub_hex

# ---- Agent license token (enterprise tier) ----
TRITON_LICENSE_KEY=$license_token

# ---- License portal invite emails (optional — leave blank to return temp password in body) ----
TRITON_LICENSE_SERVER_RESEND_API_KEY=
TRITON_LICENSE_SERVER_RESEND_FROM_EMAIL=
TRITON_LICENSE_SERVER_RESEND_FROM_NAME=
TRITON_LICENSE_SERVER_LOGIN_URL=http://localhost:8081/ui/#/login

# ---- Report server invite emails (optional) ----
REPORT_SERVER_RESEND_API_KEY=
REPORT_SERVER_RESEND_FROM_EMAIL=
REPORT_SERVER_RESEND_FROM_NAME=Triton Reports
EOF

err "done — redirect stdout to .env and run 'podman compose --profile server --profile license-server up -d'"
