package keyquality

import (
	"crypto/rsa"
	"math/big"
)

// rocaGenerators holds the 17 small primes used by the ROCA fingerprint
// test (Nemec et al., CCS 2017). For each prime p, an Infineon-generated
// modulus N satisfies: N ≡ 65537^a * 2^b (mod p) for some small a,b.
// A modulus that matches the discriminant for all 17 primes is suspected
// ROCA; any mismatch clears the key.
var rocaGenerators = []uint64{
	11, 13, 17, 19, 37, 53, 61, 71, 73,
	79, 89, 97, 103, 107, 109, 127, 151,
}

// rocaCheck runs the ROCA discriminant test on an RSA public key.
// ~0.05% false-positive rate on non-Infineon keys (per the paper).
func rocaCheck(pub *rsa.PublicKey) (Warning, bool) {
	if pub == nil || pub.N == nil || pub.N.Sign() <= 0 {
		return Warning{}, false
	}
	for _, g := range rocaGenerators {
		if !rocaMatchesGenerator(pub.N, g) {
			return Warning{}, false
		}
	}
	return Warning{
		Code:     CodeROCA,
		Severity: SeverityCritical,
		Message:  "modulus matches Infineon weak-prime structure (suspected)",
		CVE:      "CVE-2017-15361",
	}, true
}

// rocaMatchesGenerator returns true iff N mod p is in the subgroup of
// (Z/pZ)* generated by 65537 and 2. Implements the Nemec et al. ROCA
// discriminant for a single generator prime p.
func rocaMatchesGenerator(n *big.Int, p uint64) bool {
	pMod := new(big.Int).SetUint64(p)
	nModP := new(big.Int).Mod(n, pMod)
	if nModP.Sign() == 0 {
		// N divisible by generator — another problem (SMALL-PRIME catches it),
		// but ROCA clears on any non-match.
		return false
	}
	target := nModP.Uint64()
	pU := p
	base65537 := uint64(65537) % pU
	// Walk powers of 65537 mod p until we cycle back to 1.
	power65537 := uint64(1)
	seen65537 := make(map[uint64]bool, pU)
	for !seen65537[power65537] {
		seen65537[power65537] = true
		// For this a, walk powers of 2 mod p.
		candidate := power65537
		seen2 := make(map[uint64]bool, pU)
		for !seen2[candidate] {
			seen2[candidate] = true
			if candidate == target {
				return true
			}
			candidate = (candidate * 2) % pU
		}
		power65537 = (power65537 * base65537) % pU
	}
	return false
}
