package keyquality

import (
	"crypto/rsa"
	"math/big"
)

// rocaGenerators holds the 17 small primes used by the ROCA fingerprint
// test (Nemec et al., CCS 2017). For each prime p, an Infineon-generated
// modulus N satisfies: N ≡ 65537^a * 2^b (mod p) for some small a,b.
// A modulus that matches the discriminant for all 17 primes is suspected
// ROCA; any mismatch clears the key.
var rocaGenerators = []uint64{
	11, 13, 17, 19, 37, 53, 61, 71, 73,
	79, 89, 97, 103, 107, 109, 127, 151,
}

// rocaCheck runs the ROCA discriminant test on an RSA public key.
// ~0.05% false-positive rate on non-Infineon keys (per the paper).
func rocaCheck(pub *rsa.PublicKey) (Warning, bool) {
	if pub == nil || pub.N == nil || pub.N.Sign() <= 0 {
		return Warning{}, false
	}
	// For every generator prime p, we test whether N is in the multiplicative
	// subgroup generated by 65537 modulo p. If N mod p lies outside that
	// subgroup for ANY generator, the key is definitely not ROCA.
	base := big.NewInt(65537)
	mod := new(big.Int)
	for _, g := range rocaGenerators {
		pMod := new(big.Int).SetUint64(g)
		// Discriminant: walk the cyclic subgroup powers of 65537 mod p up to
		// ord(65537, p). If N mod p appears in the trace, this prime matches.
		nModP := new(big.Int).Mod(pub.N, pMod)
		if nModP.Sign() == 0 {
			// N is divisible by a generator — another (SMALL-PRIME) problem,
			// but ROCA check can't conclude. Treat as non-match (clears ROCA).
			return Warning{}, false
		}
		seen := new(big.Int).SetInt64(1)
		found := false
		// Order of 65537 mod any of the generators is at most pMod-1, which
		// for our primes is ≤ 150. Cheap bounded loop.
		for step := uint64(0); step < g; step++ {
			if mod.Set(seen).Cmp(nModP) == 0 {
				found = true
				break
			}
			seen.Mul(seen, base)
			seen.Mod(seen, pMod)
		}
		if !found {
			return Warning{}, false
		}
	}
	return Warning{
		Code:     CodeROCA,
		Severity: SeverityCritical,
		Message:  "modulus matches Infineon weak-prime structure (suspected)",
		CVE:      "CVE-2017-15361",
	}, true
}
